import { MainLayout } from '@/components/layouts/MainLayout'
import { Navbar } from '@/components/Navbar'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

/**
 * - El nombre de los componentes de página (nombre de la función) no tiene relación con el nombre del archivo que los contiene
 * - Los componentes de página se deben exportar por defecto
 * - El archivo de componente de página, debe estar en minúsculas
 * - El nombre del archivo del componente de página, se relaciona con el nombre de ruta - about.js -> /about
 */

export default function HomePage() {
  return (
    <MainLayout>
      <Head>
        <title>Bienvenidos a NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Invocar un componente personalizado de React */}
      <Navbar />
      <main className={styles.main}>
         <h2 className={styles.title}>Página <span className={styles.page}>Home</span></h2>
          {/* 
          NextJS hace uso de static side rendering en la mayoría de los escenarios
          para ello es importante hacer uso de su componente Link, para que cargue en memoria el contenido de las páginas asociadas con el enlace
          Se puede seguir usando <a>, pero esto hace un full refresh (request) de la página - (esto es recomendado para pàginas externas)
         */}
         <p className={styles.description}>Visitar la página de <Link href="/about" className={styles.link}>About</Link></p>
      </main>
    </MainLayout>
  )
}
